SELECT 
    c.CATEGORY,
    SUM(f.TOTAL_VALUE_SALES) AS total_sales
FROM FACT_SALES f
JOIN DIM_PRODUCT p 
    ON f.ITEM_CODE = p.ITEM
JOIN DIM_CATEGORY c 
    ON p.CATEGORY = c.ID_CATEGORY
GROUP BY c.CATEGORY;